#!/usr/bin/env python3
"""
Generate additional Trino-visible Hive and Iceberg fixture SQL.

The defaults are intentionally moderate: enough objects to exercise Trino
catalog/schema/table/view/partition metadata paths without making local setup
unreasonably slow.
"""

import os


HIVE_SCHEMAS = int(os.environ.get("TRINO_HIVE_FEATURE_SCHEMAS", "4"))
HIVE_TABLES_PER_SCHEMA = int(os.environ.get("TRINO_HIVE_TABLES_PER_SCHEMA", "6"))
ICEBERG_SCHEMAS = int(os.environ.get("TRINO_ICEBERG_FEATURE_SCHEMAS", "3"))
ICEBERG_TABLES_PER_SCHEMA = int(os.environ.get("TRINO_ICEBERG_TABLES_PER_SCHEMA", "4"))

ICEBERG_PARTITIONING = [
    "day(event_ts)",
    "month(event_ts)",
    "year(event_ts)",
    "bucket(account_id, 8)",
    "truncate(region, 2)",
    "event_date",
]


def emit(line: str = "") -> None:
    print(line)


def generate_hive() -> None:
    emit("-- Generated Hive feature coverage.")
    for schema_idx in range(1, HIVE_SCHEMAS + 1):
        schema = f"feature_hive_{schema_idx:03d}"
        emit(
            f"CREATE SCHEMA IF NOT EXISTS hive.{schema} "
            f"WITH (location = 's3a://hive/{schema}/');"
        )
        emit()

        for table_idx in range(1, HIVE_TABLES_PER_SCHEMA + 1):
            table = f"partitioned_events_{table_idx:03d}"
            emit(f"CREATE TABLE IF NOT EXISTS hive.{schema}.{table} (")
            emit("    event_id    BIGINT,")
            emit("    customer_id BIGINT,")
            emit("    amount      DOUBLE,")
            emit("    event_ts    TIMESTAMP,")
            emit("    payload     VARCHAR,")
            emit("    dt          VARCHAR,")
            emit("    region      VARCHAR")
            emit(") WITH (")
            emit("    format            = 'PARQUET',")
            emit(
                f"    external_location = 's3a://hive/{schema}/{table}/',"
            )
            emit("    partitioned_by    = ARRAY['dt', 'region']")
            emit(");")
            emit()

        view_table = "partitioned_events_001"
        emit(f"CREATE OR REPLACE VIEW hive.{schema}.vw_event_rollup AS")
        emit("SELECT")
        emit("    dt,")
        emit("    region,")
        emit("    count(*) AS event_count,")
        emit("    sum(amount) AS total_amount,")
        emit("    max(event_ts) AS last_event_ts")
        emit(f"FROM hive.{schema}.{view_table}")
        emit("GROUP BY dt, region;")
        emit()


def generate_iceberg() -> None:
    emit("-- Generated Iceberg feature coverage.")
    for schema_idx in range(1, ICEBERG_SCHEMAS + 1):
        schema = f"feature_iceberg_{schema_idx:03d}"
        emit(
            f"CREATE SCHEMA IF NOT EXISTS iceberg.{schema} "
            f"WITH (location = 's3a://iceberg/{schema}/');"
        )
        emit()

        for table_idx in range(1, ICEBERG_TABLES_PER_SCHEMA + 1):
            table = f"partitioned_facts_{table_idx:03d}"
            transform = ICEBERG_PARTITIONING[
                (schema_idx + table_idx - 2) % len(ICEBERG_PARTITIONING)
            ]
            emit(f"CREATE TABLE IF NOT EXISTS iceberg.{schema}.{table} (")
            emit("    event_id   BIGINT,")
            emit("    account_id BIGINT,")
            emit("    event_ts   TIMESTAMP(6),")
            emit("    event_date DATE,")
            emit("    region     VARCHAR,")
            emit("    payload    VARCHAR,")
            emit("    amount     DECIMAL(12, 2)")
            emit(") WITH (")
            emit(f"    location     = 's3a://iceberg/{schema}/{table}/',")
            emit(f"    partitioning = ARRAY['{transform}']")
            emit(");")
            emit()


def main() -> None:
    emit("-- Generated by scripts/trino-feature-generate.py.")
    emit(
        "-- Knobs: TRINO_HIVE_FEATURE_SCHEMAS, TRINO_HIVE_TABLES_PER_SCHEMA, "
        "TRINO_ICEBERG_FEATURE_SCHEMAS, TRINO_ICEBERG_TABLES_PER_SCHEMA."
    )
    emit()
    generate_hive()
    generate_iceberg()


if __name__ == "__main__":
    main()
